### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by zzm-hl** [tsadja/ShaSTA#1]
thanks for your wonderful work, hope to release the code

**Comment by nnop** [comment]
+1

**Comment by tsadja** [comment]
Hi, sorry for my delayed response. After my initial submission in November, I added additional features that significantly boosted the results. I am currently cleaning up code (again!) and preparing a link where you can directly download all the preprocessed data to save yourself time from running all the preprocessing. I will be done with this by the end of the month. Thank you for your patience!

**Comment by tsadja** [comment]
Update: code and preprocessed data have been released. Please see README and docs/DATA for more information.
