### ISSUE TITLE
Hello, I encountered a problem while replicating your code

### ISSUE THREAD

**Issue by Mrzhoujian** [tsadja/ShaSTA#2]
Hello, I encountered a problem while replicating your code, indicating that the merged_cp_val.json file is missing. Could you please provide this file? I want to reproduce the accuracy of the car with the model you provided.

**Comment by tsadja** [comment]
Hi, thank you for your question. I haven't looked at this codebase in over a year, but I think that file is referring to val_tracking_result.json which can be found from this download:
wget http://download.cs.stanford.edu/juno/ShaSTA/results.zip
unzip results.zip

**Comment by Mrzhoujian** [comment]
> Hi, thank you for your question. I haven't looked at this codebase in over a year, but I think that file is referring to val_tracking_result.json which can be found from this download: wget http://download.cs.stanford.edu/juno/ShaSTA/results.zip unzip results.zip

I'm glad to receive your reply, but I get this error when using the val_tracking_result.json file you mentioned;
Traceback (most recent call last):
File "tools/nusc_shasta/pub_test.py", line 199, in <module>
main()
File "tools/nusc_shasta/pub_test.py", line 121, in main
outputs = tracker.step_centertrack(preds, time_lag)
File "/home/dell/MM3D/ShaSTA/tools/nusc_shasta/pub_tracker_merged.py", line 86, in step_centertrack
if det['detection_name'] ! = nusc_name:
KeyError: 'detection_name'
I've never been able to solve it

**Comment by tsadja** [comment]
I see what's going on. You are using the functions that take in the detections and forms tracks. I released my final tracks in val_tracking_result.json. So if you want to see the numerical results for that you can just call the eval_tracking() function in pub_test.py. Basically, you can comment out lines 198 and 199 in pub_test.py and run the script. Make sure to change the name of val_tracking_result.json to tracking_result.json since line 166 is expecting that file name.

**Comment by Mrzhoujian** [comment]
> I see what's going on. You are using the functions that take in the detections and forms tracks. I released my final tracks in val_tracking_result.json. So if you want to see the numerical results for that you can just call the eval_tracking() function in pub_test.py. Basically, you can comment out lines 198 and 199 in pub_test.py and run the script. Make sure to change the name of val_tracking_result.json to tracking_result.json since line 166 is expecting that file name.

The problem has been solved successfully. Thank you for your reply.
